### ISSUE TITLE
Number of PCA components

### ISSUE THREAD

**Issue by lbanellis** [anaston/cca_pls_toolkit#12]
Thank you again for an amazing CCA and easy to implement toolbox.

I just want to check my understanding of the number of PCA components when these are selected via parameter optimisation (cfg.machine.param.crit = 'correl';).

They seem to change a lot for each cca for each data split (I am looking in the param_1.mat file in the res folder for each level). 

<img width="169" alt="image" src="https://user-images.githubusercontent.com/94465218/203762754-1c1092be-4f77-4602-ba31-8f1af374f5ab.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/94465218/203762805-967bb579-d64e-4be7-ab3a-2cf2df9ce802.png">
<img width="155" alt="image" src="https://user-images.githubusercontent.com/94465218/203762850-4e2fc31d-9ab2-44cf-b4e8-20cd63f33a3f.png">

Is it normal for the number of PCA components to change a lot for each cca? 

Also, I noticed I had 3 levels but I'm not sure why?

Finally, the p values for level one seem to always be 0.0010 (in the results_table.txt in the res - level1 folder). Is this correct?

attached is my code in case it helps.

[test.m.zip](https://github.com/anaston/cca_pls_toolkit/files/10083629/test.m.zip)

Thanks in advance and best wishes

Leah Banellis

**Comment by lbanellis** [comment]
Furthermore for some permutations I got this error: 

Warning: Ambiguous syntax: First and second arguments are both scalars.
 Use EIGS(A,[],K,SIGMA) to specify standard eigenvalue problem, or EIGS(A,B,K,SIGMA) to specify
 generalized eigenvalue problem. 
> In eigs>isBpresent (line 547)
In eigs>checkInputs (line 232)
In eigs (line 90)
In rcca (line 39)
In run_machine (line 38)
In run_model (line 261)
In main (line 63)
In main (line 82)
In main (line 82)
In test (line 48)

**Comment by anaston** [comment]
Thanks, good questions! I will reply to each in a separate comment.

**Comment by anaston** [comment]
Regarding the number of PCA components, plotting the hyperparameter surface could give some insights what is happening. I would suggest to use use `correl`,`exvarx` and `exvary` (and perhaps `trexvarx`, `trexvary`) as metrics to see how they change as a function of the number of principal components (you would also need to define these in your `cfg.machine.metric` before you run the analysis, otherwise they won't be saved on disc). For instance, if the global maximum is broad, i.e., different number of components give similar out-of-sample correlation (`correl`) then it would explain why the number of components vary a lot. Another possibility could be that the associative effects are not that robust (e.g. due to sample size) and hence the hyperparameter surface changes across data splits resulting in different global optima. You can also find some more information on these in the following links:

- (see https://mlnl.github.io/cca_pls_toolkit/mfiles/plot_paropt/)
- https://mlnl.github.io/cca_pls_toolkit/cfg/#machine (see .metric)
- https://mlnl.github.io/cca_pls_toolkit/visualization/#hyperparameters

**Comment by anaston** [comment]
Regarding the levels, they relate to the associative effects. The toolkit finds the associative effects iteratively, and searches for the next effect if the current one is significant. Having 3 levels in your `res` folder means that 2 associative effects were significant and the toolkit stopped at the third one as it was not significant. The p value depends on the number of permutations - if you use 1000 permutations (`cfg.stat.nperm = 1000`) then the smallest p value you can get is 0.001.

**Comment by anaston** [comment]
Thanks for sharing the warning, it occurs when a single scalar is passed to MATLAB's built-in eigs function instead of a covariance matrix. This can happen, for instance, when both data modalities have a rank of 1. The results will be still correct, but there is no need to solve an eigenvalue problem, that's why the warning. I might suppress this warning in the future so that users are not prompted with it.

**Comment by lbanellis** [comment]
Thank you for your quick and detailed response, it has really helped and expanded my understanding! 

I have a few more questions (I hope it's ok). 

1. I also get this error occasionally, just want to check:
_Warning: Dimensionality of data X is lower than number of PCA components  > In get_featid (line 39) In load_data (line 270) In run_model (line 96) In main (line 54) In test (line 48)_

2a. In the full demo it states "_Note, that that sign of the model weights or latent variables is arbitrary and can be changed for convenience (e.g., to compare results across models)._". I was under the impression that the sign of the weights can be meaningful (for example when using connectivity data, I thought potentially negative weights reflected inhibition and positive excitation, is this not accurate? 

2b. Furthermore, I noticed my weights for the connectivity data are very low (e-05 - e-06 values). In a different CCA pipeline I am using, we usually get some values at least above 0.2 (& we use this for plotting a thresholded connectivity chord plot or brain maps). Am I misunderstanding the weights in some way? (my understanding is they reflect correlations of the canonical variates with the input data?). Is there another reason they are so low?

3. A low level question of the confounds variable ('C.m'): are there any recommendations for the coding of binary confounds (gender) for cca? (currently I'm using -1 and 1). I am currently not z-scoring, but I'm wondering if I should? (also with the behavioural Y.m matrix). Should an intercept be included in the confounds?

Thank you again for your efforts with this. It is really appreciated.

**Comment by anaston** [comment]
Please see my thoughts below in separate comments.

**Comment by anaston** [comment]
The warning about the principal components is fine, the toolkit automatically adjusts the number of principal components if needed.

**Comment by anaston** [comment]
The sign of a particular weight is arbitrary indeed, however, the overall sign of a pair of brain-behavioural weights is not. For instance, behavioural item 1 with positive weight and brain connection 1 with positive weight is the same as behavioural item 1 with negative weight and brain connection 1 with negative weight. Similarly, behavioural item 2 with positive weight and brain connection 2 with negative weight is the same as behavioural item 2 with negative weight and brain connection 1 with positive weight. Normally one is interested in how an increase or decrease in a brain variable is related to an increase or decrease in a behavioural variable, so this arbitrariness is not really a problem. However, in case of connectivity data, things a bit more complicated as an increase in model weight can mean a strong connection becoming stronger or a weak connection becoming weaker. In my experience, loadings (to use these, see `res.gen.weight.type` at https://mlnl.github.io/cca_pls_toolkit/res/#gen) are easier to interpret working with connectivity data as you directly compare the original variable with the latent variable, however, one needs to be cautious when using loadings. We included a section about this in the Supplement of our [tutorial paper](https://doi.org/10.1016/j.bpsc.2022.07.012) (see Interpretation of model weights).

**Comment by anaston** [comment]
The overall value of the model weights is arbitrary in CCA/PLS analyses, and they depend on how you formulate the optimization. Note that here I refer to the weights optimized by the algorithm. Feel free to normalize the weights, the toolkit offers options for that (see the `weight.norm` settings in the `res` structure). The correlation between the input variables and the canonical variates is the loading I was referring to in my previous comment, they allow similar interpretation than the weights and indeed their values should be similar across analyses.

**Comment by anaston** [comment]
By default, each variable is z-scored in the toolkit in the beginning of the analysis, so it doesn't matter how you encode a binary variable as a single column. You can also hot encode gender, i.e., one column for males and one column for females (1 if a gender is met and 0 otherwise). The latter is what I would recommend in general as it is easier to interpret (they appear with opposite weights and no need to think about how you encoded them), however, in case of SPLS you might run into convergence problems if only gender is included in a model. The toolkit automatically adds an intercept to the confounds if it's not included.

**Comment by lbanellis** [comment]
Thank you this is all super useful :)
