### ISSUE TITLE
Extracting Weight Stability and Explained Variance

### ISSUE THREAD

**Issue by lbanellis** [anaston/cca_pls_toolkit#14]
To whom it may concern

Thank you again for all your help with the toolkit. I am writing up my CCA results with your toolkit and I just want to check my understanding when extracting Weight Stability (& and few other metrics).

You state in your paper "the stability of the CCA/PLS models can be measured as the average similarity of weights across different splits of training data". 

I load the 'simwx' and 'simwy' variables from '/res/level1/model_1.mat' for the significant CCA level/mode. I notice there are 4 columns and 5 rows (I assume 5 rows are for each data split). Should the Weight Stability be computed as the average across the 4 columns for the best data split? (i.e., mean(simwx(res.frwork.split.best,:)) )?

Furthermore, when using the predictive approach should the explained variance reported be of out-of-sample also? (exvarx and exvary)? & should it be for the best data split also? (i.e., exvarx(res.frwork.split.best) )?

Finally, I'm assuming there is no p-value for the in-sample correlation when using the predictive approach (as the p values will be computed using the out-of-sample correlation)?

Thanks in advance, I've really enjoyed using the toolkit for my paper!

Best wishes

Leah

**Comment by anaston** [comment]
Hi Leah, it's great to hear that the toolkit was useful for your project!

Indeed, if you want to have weight stability as a single summary statistic, then the approch you described is the way to go. Note that the weight stability is calculated between each pair of weights, that's why you have an n x (n-1) matrix, where n stands for the out splits. This also means that each value occurs twice in this matrix, for instance, the similarity between splits 1 and 2 can be found at indexes (1,2) and (2,1) and thus you would need to discard half of the values  if you wanted to make inference on all similarity values.

Regarding explained variance, I would suggest to report in-sample explained variance for the best data split. This is the approach we also took in our tutorial paper even though we used the predictive approach in all analyses (except of one) as you do. The reason is two-fold: i) in the literature, explained variance is often reported for in-sample analyses; ii) we started using explained variance in the toolkit only recently and thus haven't accumulated much experience with the out-of-sample version of it it to be able to recommend.

Yes, the p-value is calculated only for a single metric, the one defined by `cfg.stat.crit`. The default and our recommendation is to use out-of-sample correlation denoted by `correl`. The in-sample correlation is often inflated and thus could bias the statistical inference.

Cheers, Agoston

**Comment by lbanellis** [comment]
Hi Agoston

Thank you for your swift response and explaining the summary statistic variables! Just to check, am I right in thinking the weight stability should be averaged in the best data split only? Or is it best to use all of the values?

Finally, if calculating SEM of the metrics like you do in your paper, I'm assuming you calculate this across all of the data splits?

Thank you again

Leah

**Comment by anaston** [comment]
In our tutorial paper we calculated mean and SEM across all available measures. I.e., given 10 outer splits, this would mean calculating mean and SEM across 10 measures for correlation and explained variance but across 45 measures (due to pairwise comparisons) for stability.

Calculating average stability for the best split makes more sense if you want to report metrics only for the best split.

**Comment by lbanellis** [comment]
Thank you!

**Comment by anaston** [comment]
You are welcome! :)
