### ISSUE TITLE
How to know if cca is being parallelized when running on cluster

### ISSUE THREAD

**Issue by lbanellis** [anaston/cca_pls_toolkit#15]
Really sorry to message again. I am trying to run the toolkit on the cluster (considering a semi-multiverse approach). The script runs via SLURM, however it seems quite slow (the same time as when run it as cfg.env.comp ='local').

I've attached my scripts

[cca_scripts.zip](https://github.com/anaston/cca_pls_toolkit/files/11223152/cca_scripts.zip)

Thanks in advance,
Leah

**Comment by anaston** [comment]
Hi Leah,

The toolkit achieves parallellization in a cluster environment using job arrays. These are defined by the #SBATCH --array option in your .sh file (for details, see https://slurm.schedmd.com/job_array.html). When the toolkit runs a job array in a SLURM environment, it accesses the index of the job array via `getenv('SLURM_ARRAY_TASK_ID')` and saves it as `cfg.env.fileend`. This job array index will be added as suffix to the filenames to ensure paralllization across the job array. For further details, please see https://mlnl.github.io/cca_pls_toolkit/getting_started/#running-on-a-cluster.

You analysis file is ok, so the issue is probably on your cluster side. The first thing you could check is whether your analysis runs on a job array as expected (for details, see https://slurm.schedmd.com/squeue.html). Then you might want to double check that all settings in your .sh file are fine (for details, see https://slurm.schedmd.com/sbatch.html).

After having a quick look at your .sh file, the memory setting seems unusual. Are you sure you need 100GB per job? Your cluster might not have many nodes with that memory. Also, note that you need to specify the memory using the suffix K|M|G|T, i.e. it would be `100G` in your case.

In your analysis file, I also spotted the following line: `cfg.machine.param.nPCAy = 1; % no PCA for Y (beh data) so set to 1
`. I just want to double check whether you have 1 variable in your Y data. If yes, then all good, however, if you have more variables in your Y data then with this setting the toolkit will reduce your Y data to 1 principal component.

Agoston

**Comment by lbanellis** [comment]
Hi Agoston

Thank you again for your detailed response.

Just to comment on the PCAy parameter: I set this to 1 because you suggested this in a previous email (the initial one I sent asking for guidance if I wanted to do pca with x but not pca with y - but maybe I misunderstood). When I look in the results_table.txt, 'npcay=7' for each split, when I do this with 7 behavioural factors for y (and 'npcay=21' when I run cca with 21 behavioural items for y). Thus, it was my understanding that 'cfg.machine.param.nPCAy = 1;' is not reducing the y to 1 principal component? Unless, I am misunderstanding something? 

I will check the slurm details, thank you for your support with this. I tried with '--mem' set to much lower also, I was seeing if I set the total memory for the job to much higher if it would make a difference (we have our own cluster for the lab so it is possible to set this to fairly high - as long as per job indicates the whole cca script (and not different parallel parts of it?)). 

Thanks again!
Leah

**Comment by anaston** [comment]
Hi Leah,

I am sorry, I overlooked the name of the field. nPCAy indeed sets the number of principal components to their maximum value in an indirect way, so your settings are good. I thought I was referring to PCAy which sets the number of principal components directly.

Agoston

**Comment by lbanellis** [comment]
Hi Agoston

No worries, and thank you for checking also. 

I have tried many different slurm settings ('--mem-per-cpu'=2G / 20G , or instead '--mem=' 2G / 100G / 20G , '--cpus-per-task'=2 / 6 , '--ntasks=' 1 / 2 / 3). But each time, when I check cfg.env.fileend, it always ends in '_1' and in 'squeue' there is only one job listed (rather than an array of jobs as I kept '--array'=1-100 the same each time).

I always kept cfg.env.comp = 'cluster'; in the matlab script.

Is there anything else I can try?

Thanks again for all your help.

Leah

**Comment by anaston** [comment]
Hi Leah,

Can you try using the attached job file? You could also omit the memory setting and I believe it would use the default memory setting on your cluster.

[cca_jobs_slurm_am.sh.zip](https://github.com/anaston/cca_pls_toolkit/files/11325579/cca_jobs_slurm_am.sh.zip)

Best,
Agoston

**Comment by lbanellis** [comment]
Hi Agoston

Thank you so much! The script you attached successfully parallelised the CCA. It ran in 4 minutes instead of 40 minutes and cfg.env.fileend = '_17'  (although another time was still '_1' but did run parallelised in 5 mins). 

Just to note, the log files are now split across 100 (for each of the arrays I assume), maybe that is ok. But is it possible to print just one log? 

There is also an error noted at the end of the logs (can be slightly different across the log arrays):

```
'[Warning: cfg structures are not the same, be very cautious!] 
[> In savemat (line 48)
In cfg_defaults (line 520)
In RunCCA (line 45)] 
cfg.env.fileend with different value
cfg.env.seed.model with different value'
```

or:

```
'{Error using movefile
Unknown error occurred.

Error in renamemat (line 40)
        movefile(old_file, new_file);

Error in cleanup_files (line 65)
    renamemat(cfg, fullfile(res.dir.perm, 'allperm.mat'));'
```


I believe this error is associated with 'cleanup_files(cfg);' in the cca matlab script.

**Comment by anaston** [comment]
Hi Leah,

I am glad to hear that the analysis ran successfully on the cluster and thanks for pointing out these issues.

Normally, I would recommend to have one log file per node, as it allows to track down potential issues on a particular node. However, you can also have a single log file which includes outputs from all nodes, please consult https://slurm.schedmd.com/sbatch.html or your system administrator on how to do that.

The warning lets the user know that the `cfg` file saved on the disc is different from the `cfg` structure set by the node. This is what happens if another node saved the `cfg` file, so it is a normal behaviour in a cluster environment. I will consider revising the toolkit code so that `cfg.env.fileend` will be set to '_1' after running `cleanup_files.m`, thanks for pointing this out.

Regarding the error: `cleanup_files.m` deletes and renames files, which is not safe to do in multiple nodes at the same time. Thus if you work in a cluster environment, it is recommended to run this function manually in a single interactive node once the array of nodes completed the analysis (i.e., not part of your RunCCA file). Thanks, I will amend the documentation to point this out.

Best,
Agoston

**Comment by lbanellis** [comment]
Hi Agoston

Thank you for all your help with this. I will run cleanup_files after running on the cluster in a single interactive node.

All the best!

Leah
