### ISSUE TITLE
Problem with cfg.machine.param.crit = 'correl+simwxy';

### ISSUE THREAD

**Issue by enicolaisen** [anaston/cca_pls_toolkit#16]
Hello!

I am having a problem when I set `cfg.machine.param.crit = 'correl+simwxy' `. 
I get the error:

```
Reference to non-existent field 'simwx'.

Error in get_hyperparam (line 86)
                        nanmean([S.simwx(i,:); S.simwy(i,:)], 1)));

Error in run_model (line 153)
            param = get_hyperparam(res, 'grid');

Error in main (line 57)
run_model(res, 'main');

Error in rcca_a1_test (line 53)
main(cfg);
```

However, if I set `cfg.machine.param.crit = 'correl'`; there is not problem.

Thanks a lot in advance!

**Comment by anaston** [comment]
Hi Eli,

The basic metrics that the toolkit calculates and saves are defined by `cfg.machine.metric`. Other fields like `cfg.machine.param.crit` and `cfg.stat.crit` do not calculate metrics but only make use of those defined by `cfg.machine.metric`. In the case of `cfg.machine.param.crit = 'correl+simwxy'` the toolkit makes use of the metrics `'correl'`, `'simwx'` and `'simwy'`, so these all need to be defined by `cfg.machine.metric`. Most likely that wasn't the case in your settings and that's why you got the error.

Let me know if that works.

Agoston

**Comment by enicolaisen** [comment]
Hi Agoston,

thanks a lot for the clarification. If I run the toolkit with `cfg.machine.metric = {'correl','simwx','simwy'}` and `cfg.machine.param.crit = 'correl+simwxy'` I get the following error:

```
Running hyperparameter optimization
hyperparameter id: 1 (out of 100), split id: 1 (out of 5)...Index exceeds the number of array elements (0).

Error in parse_struct (line 42)
if numel(S) > 1 && size(S(1).(fields{1}), dim) ~= 1

Error in run_model (line 105)
                        name_value = parse_struct(S, 2);

Error in main (line 54)
run_model(res, 'gridsearch');

Error in rcca_a1_correlsimwxy (line 54)
main(cfg);
```

However, if I change to `cfg.machine.metric     = {'correl','simwx','simwy'}` it runs well. Not sure if it does consider the three criteria though. So maybe the documentation is outdated? (In the section Defaults - cfg - machine - param.crit)

Thanks!

Best,
Eli

**Comment by anaston** [comment]
Hi Eli,

Could you send your cfg file for me to be able to replicate the error? If you could easily send some test data that might be also helpful but perhaps I won't need that.

Setting `cfg.machine.metric = {'correl', 'simwx', 'simwy'}` and `cfg.machine.param.crit = 'correl+simwxy'` should work so perhaps it is a bug or the issue is some other setting or how these settings interact with those in your specific analysis.

Best,
Agoston

**Comment by enicolaisen** [comment]
Thanks Agoston!

Actually, I cannot reproduce the error I posted in my last message. As you said, these settings work well.

I am sorry for the confusion.

Best,
Eli
