### ISSUE TITLE
Setting different "data" parameters for X and Y

### ISSUE THREAD

**Issue by pauldhami** [anaston/cca_pls_toolkit#18]
Greetings Agoston,

I was wondering if there are ways to set different "data" parameters for X and Y. 

Specifically, I was wondering if:

- can I apply normalization ('zscore') to my biological data (X) but not my behavioural data (Y)?
- can I deconfound X and Y with each having a different set of confounds? From what I can see, I can deconfound both X and Y, or one and not the other (with 'none'), but am unsure if there is an available way to have two different sets of variables to use for deconfounding separately in X and Y. 

If I can also ask a slightly unrelated question:for the zscore normalization in the context of CCA-PCA, I'm assuming the normalization is done to the input features (i.e., PCA components) which are then used for CCA (and not for the raw X variables prior to PCA being done)?

Thank you for all your help,
Paul

**Comment by anaston** [comment]
Hi Paul,

Thanks for your questions.

Yes, you can set preprocessing separately for `X` and `Y`. In particular,

- if you want to z-score only `X` then `cfg.data.X.preproc` should include `'zscore'` but `cfg.data.Y.preproc` should not include that. Sorry, I just see that the documentation is outdated (`preproc` is said to be a field of `data` but in the latest version it is the field of each data modality), this has been a relatively recent development and the documentation hasn't been updated accordingly but I will fix it soon.

- I am afraid you cannot use a different set of confounds for `X` and `Y` at the moment. However, this feature could be easily added to the toolkit if you were interested doing so. For instance, you could add all confounds to your `C.mat` file and define a data modality specific field for the index of confounds you want to use, e.g. `cfg.data.X.idconf = 1:3` and `cfg.data.Y.idconf = 4:5` then modify `preproc_data.m` so that these indices are applied when the deconfounding is performed. If you are happy to contribute to the toolkit then please make a pull request with these changes. If you were to do so, then please also ensure that the default settings of `idconf` in `cfg_defaults.m` is set to use all confounds to make it compatible with the current functionality.

Regarding to your last question, the preprocessing is always performed on the raw data, i.e., in case of PCA-CCA this is performed before the PCA step. The reason behind this is that PCA is sensitive to the scaling of the data and zscoring the features before PCA ensures that none of the original features drive the optimization just because their scale is larger.

Best,
Agoston

**Comment by pauldhami** [comment]
Hi Agoston,

Thank you for your very helpful replies. Regarding 2, that's something I can definitely look into as such modifications would be helpful for my current work anyways.

Regarding normalization (and sorry this isn't exactly a toolkit related question), do you have any thoughts on performing normalization then both before PCA (as you mentioned) and then again on the components prior to CCA? My initial thinking was if I was working with data all from one modality (e.g., my X is cortical thickness values from different ROIs, so all are on the same scale), and due to the decrease in variance in PCA components, it would make sense to normalize the PCA values (rather than the raw cortical thickness values) prior to submitting the components to CCA (I very well could be wrong in my understanding...). 

Thanks again, and happy holidays,
Paul
